In [1]:
                                                # Artificial Neural Network #

In [2]:
# Part 1 - Data Preprocessing

In [51]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [52]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [53]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [54]:
# Encoding categorical data(Geography)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [55]:
# Encoding categorical data(Gender)
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [105]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X

C:\Users\Ramu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Ramu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.0000000e+00, 0.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [57]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [58]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
# Part 2 - Now let's make the ANN!

In [60]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [61]:
# Initialising the ANN
classifier = Sequential()

In [67]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [68]:
# Adding second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [69]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [74]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) # optimize the weights, calculate the loss function and automatically measure the accuracy

In [102]:
# Fitting the ANN to the Tranning set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3996 - accuracy: 0.8361
Epoch 2/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3995 - accuracy: 0.8359
Epoch 3/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3994 - accuracy: 0.8360
Epoch 4/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3995 - accuracy: 0.8355
Epoch 5/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3994 - accuracy: 0.8350
Epoch 6/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.3997 - accuracy: 0.8345
Epoch 7/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.3992 - accuracy: 0.8357
Epoch 8/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.3993 - accuracy: 0.8364
Epoch 9/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3995 - accuracy: 0.8335
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 2s 191us/step - loss: 0.3927 - accuracy: 0.8360
Epoch 79/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3930 - accuracy: 0.8371
Epoch 80/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.3922 - accuracy: 0.8359
Epoch 81/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.3926 - accuracy: 0.8366
Epoch 82/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.3922 - accuracy: 0.8367
Epoch 83/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.3927 - accuracy: 0.8360
Epoch 84/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.3928 - accuracy: 0.8363
Epoch 85/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.3921 - accuracy: 0.8360
Epoch 86/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3919 - accuracy: 0.8346
Epoch 87/100
8000/8000 [==============================] - 1

In [76]:
# Part 3 - Making predictions and evaluating the model

In [106]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [107]:
y_pred

array([[0.20973104],
       [0.2701946 ],
       [0.10072878],
       ...,
       [0.17718196],
       [0.09076592],
       [0.13575673]], dtype=float32)

In [108]:
y_pred = (y_pred > 0.5)

In [109]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [110]:
# Making a confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [111]:
cm   # confusion Matrix

array([[1548,   47],
       [ 272,  133]], dtype=int64)

In [112]:
# Measuring the Accuracy of the test set
accuracy = (1545+139)/2000
accuracy

0.842

In [ ]:
# Predicting a single new observation
Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000
    
So should we say goodbye to that customer ?

In [114]:
new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

In [115]:
new_prediction = (new_prediction > 0.5)
new_prediction

array([[False]])

In [116]:
# So the customar will not leave the Bank

In [ ]:
                                                 # Thank You #