In [1]:
# Artificial Neural Network

In [2]:
# Part 1 - Data Preprocessing

In [51]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [52]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [53]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [54]:
# Encoding categorical data(Geography)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [55]:
# Encoding categorical data(Gender)
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [56]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X

C:\Users\Ramu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Ramu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [57]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [58]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
# Part 2 - Now let's make the ANN!

In [60]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [61]:
# Initialising the ANN
classifier = Sequential()

In [67]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [68]:
# Adding second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [69]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [74]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) # optimize the weights, calculate the loss function and automatically measure the accuracy

In [75]:
# Fitting the ANN to the Tranning set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\Ramu\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 4s 515us/step - loss: 0.4926 - accuracy: 0.7952
Epoch 2/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.4302 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.4268 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.4229 - accuracy: 0.7968
Epoch 5/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.4192 - accuracy: 0.8183
Epoch 6/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.4169 - accuracy: 0.8239
Epoch 7/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.4148 - accuracy: 0.8265
Epoch 8/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.4130 - accuracy: 0.8300
Epoch 9/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.4116 - accuracy: 0.8307
Epoch 10/100
8000/8000 [==============================]

Epoch 78/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.3997 - accuracy: 0.8364
Epoch 79/100
8000/8000 [==============================] - 2s 236us/step - loss: 0.3996 - accuracy: 0.8346
Epoch 80/100
8000/8000 [==============================] - 2s 238us/step - loss: 0.3998 - accuracy: 0.8344
Epoch 81/100
8000/8000 [==============================] - 2s 250us/step - loss: 0.3997 - accuracy: 0.8346
Epoch 82/100
8000/8000 [==============================] - 2s 250us/step - loss: 0.3998 - accuracy: 0.8340
Epoch 83/100
8000/8000 [==============================] - 2s 243us/step - loss: 0.3996 - accuracy: 0.8341
Epoch 84/100
8000/8000 [==============================] - 2s 274us/step - loss: 0.3998 - accuracy: 0.8341
Epoch 85/100
8000/8000 [==============================] - 2s 251us/step - loss: 0.3997 - accuracy: 0.8351
Epoch 86/100
8000/8000 [==============================] - 2s 250us/step - loss: 0.4001 - accuracy: 0.8346
Epoch 87/100
8000/8000 [======================

In [76]:
# Part 3 - Making predictions and evaluating the model

In [88]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [84]:
y_pred

array([[0.20458466],
       [0.33387178],
       [0.15432239],
       ...,
       [0.1555371 ],
       [0.1213907 ],
       [0.10388625]], dtype=float32)

In [92]:
y_pred = (y_pred > 0.5)

In [80]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [93]:
# Making a confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [94]:
cm   # confusion Matrix

array([[1545,   50],
       [ 266,  139]], dtype=int64)

In [99]:
# Measuring the Accuracy
accuracy = (1545+139)/2000
accuracy

0.842